import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { chromium } from '@playwright/test';
import { initializeAuditBrowser } from './relay-ui-audit.server.mjs';
import { startAdditionalServer } from './relay-ui-additional-modals.server.fixture.mjs';

const output = process.env.RELAY_UI_ADDITIONAL_OUTPUT;
const evidence = process.env.RELAY_UI_ADDITIONAL_EVIDENCE;
const executable = process.env.RELAY_UI_AUDIT_BROWSER;
if (!output || !evidence || !executable) throw new Error('Own work, project evidence and existing headless browser are required');
const label = process.env.RELAY_UI_ADDITIONAL_LABEL || 'first';
const sources = {
  contact: 'src/components/main/NewContactModal.tsx', 'contact-edit': 'src/components/main/NewContactModal.tsx',
  'report-options': 'src/components/modals/reportModal/ReportModal.tsx', 'report-comment': 'src/components/modals/reportModal/ReportModal.tsx',
  country: 'src/components/common/CountryPickerModal.tsx', password: 'src/components/common/PasswordConfirmModal.tsx',
  'password-loading': 'src/components/common/PasswordConfirmModal.tsx', formatting: 'src/components/common/RemoveFormattingModal.tsx',
  'safe-link': 'src/components/main/SafeLinkModal.tsx', 'browser-close': 'src/components/main/BrowserCloseConfirmationModal.tsx',
  mute: 'src/components/left/MuteChatModal.tsx', pin: 'src/components/common/PinMessageModal.tsx',
  'delete-chat': 'src/components/common/DeleteChatModal.tsx', 'attachment-photo': 'src/components/middle/composer/AttachmentModalItem.tsx',
  'attachment-file': 'src/components/middle/composer/AttachmentModalItem.tsx', document: 'src/components/common/DocumentReaderModal.tsx',
  'chat-language': 'src/components/middle/ChatLanguageModal.tsx', 'delete-message': 'src/components/common/DeleteMessageModal.tsx',
};
await mkdir(output, { recursive: true }); await mkdir(evidence, { recursive: true });
const report = { schemaVersion: 1, generatedAt: new Date().toISOString(), label, environment: 'Actual imported components in real App MockClient; fresh headless context; public requests blocked; destructive/account callbacks intercepted before opening; no product edits', cases: [], errors: [], blockedRequests: 0, sourceHashes: {}, limits: ['AttachmentModalItem preview only; full AttachmentModal editor/upload gate', 'No live password, account, server acceptance, PDF/DOCX or premium purchase coverage', 'RTL and 200% root font are test emulations; no claim of translated locale or physical DPI device'], gates: [] };
for (const source of [...new Set(Object.values(sources))]) report.sourceHashes[source] = createHash('sha256').update(await readFile(source)).digest('hex');
const { server, url } = await startAdditionalServer(output);
let browser; let page;
const events = () => page.evaluate(() => window.__relayAdditional.events);
const count = async (name) => (await events()).filter((event) => event.name === name).length;
async function close() { await page.evaluate(() => window.__relayAdditional.close()); await page.waitForTimeout(300); }
async function open(kind) {
  await close();
  if (kind === 'document') await page.evaluate(() => window.__relayAdditional.openDocument('txt'));
  else if (kind === 'chat-language') await page.evaluate(() => window.__relayAdditional.openChatLanguage());
  else if (kind === 'delete-message') await page.evaluate(() => window.__relayAdditional.openDeleteMessage());
  else await page.evaluate((value) => window.__relayAdditional.open(value), kind);
  await page.waitForTimeout(450);
  const modal = page.locator('dialog[open], .Modal.open:not(dialog) .modal-dialog').last();
  await modal.waitFor({ state: 'visible', timeout: 20000 });
  return modal;
}
async function run(id, kind, action) {
  if (process.env.RELAY_UI_ADDITIONAL_FILTER && !new RegExp(process.env.RELAY_UI_ADDITIONAL_FILTER).test(id)) return;
  delete report.interactionTarget;
  const errorStart = report.errors.length;
  const eventStart = (await events()).length;
  try { const detail = await action(); report.cases.push({ id, source: sources[kind], status: detail?.isGate ? 'gate' : 'pass', detail, interactionTarget: report.interactionTarget, newErrors: report.errors.slice(errorStart) }); console.log('PASS ' + id); }
  catch (error) { const screenshot = `ui-additional-modal-${label}-${id}.png`; await page.screenshot({ path: path.join(evidence, screenshot) }).catch(() => {}); report.cases.push({ id, source: sources[kind], status: 'fail', error: String(error), interactionTarget: report.interactionTarget, screenshot, protectedEvents: (await events()).slice(eventStart), active: await page.evaluate(() => window.document.activeElement?.outerHTML.slice(0, 400)), newErrors: report.errors.slice(errorStart) }); console.log('FAIL ' + id + ' ' + String(error).slice(0, 180)); }
  finally { await page.keyboard.up('Enter'); await page.keyboard.up('Space'); }
}
async function geometry(modal) {
  return modal.evaluate((element) => {
    const windowObject = window; const rectangle = element.getBoundingClientRect();
    const visible = Array.from(element.querySelectorAll('button,input,textarea,[role=button]')).filter((control) => control.getClientRects().length && windowObject.getComputedStyle(control).visibility !== 'hidden');
    const outside = visible.filter((control) => { const rect = control.getBoundingClientRect(); const isOutside = rect.left < -1 || rect.right > windowObject.innerWidth + 1 || rect.top < -1 || rect.bottom > windowObject.innerHeight + 1; if (!isOutside) return false; let parent = control.parentElement; while (parent && parent !== element) { const style = windowObject.getComputedStyle(parent); const bound = parent.getBoundingClientRect(); const isScrollContainer = /auto|scroll/.test(style.overflowY) && parent.scrollHeight > parent.clientHeight + 1; if (isScrollContainer && bound.top >= -1 && bound.bottom <= windowObject.innerHeight + 1 && bound.left >= -1 && bound.right <= windowObject.innerWidth + 1) return false; parent = parent.parentElement; } return true; }).map((control) => ({ text: control.textContent?.trim().slice(0, 90), tag: control.tagName, box: control.getBoundingClientRect().toJSON() }));
    return { box: rectangle.toJSON(), bodyText: element.textContent?.trim().slice(0, 300), controls: visible.length, outsideViewport: outside, direction: windowObject.getComputedStyle(element).direction, fontSize: windowObject.getComputedStyle(element).fontSize, rootFontSize: windowObject.getComputedStyle(windowObject.document.documentElement).fontSize, typographySamples: Array.from(element.querySelectorAll('p,h1,h2,h3,button,label,input,textarea')).slice(0, 12).map((node) => { const style = windowObject.getComputedStyle(node); return { tag: node.tagName, className: node.className, text: node.textContent?.trim().slice(0, 60), fontSize: style.fontSize, lineHeight: style.lineHeight, fontFamily: style.fontFamily, fontWeight: style.fontWeight }; }) };
  });
}
try {
  const context = await chromium.launchPersistentContext(path.join(output, 'profile-' + label + '-' + Date.now()), { headless: true, executablePath: executable, viewport: { width: 1920, height: 1080 }, serviceWorkers: 'block' });
  browser = context;
  page = await context.newPage(); await page.addInitScript(initializeAuditBrowser);
  await page.route('**/*', (route) => { if (new URL(route.request().url()).hostname === '127.0.0.1') return route.continue(); report.blockedRequests += 1; return route.abort(); });
  page.on('pageerror', (error) => report.errors.push({ phase: 'pageerror', error: String(error) }));
  await page.goto(url, { waitUntil: 'domcontentloaded' });
  // Ждём именно чат 101 сценария relay-ui: два чата сценария по умолчанию (до его загрузки) тоже дают chatCount >= 2
  // Ждём именно чат 101 сценария relay-ui: два чата сценария по умолчанию тоже дают chatCount >= 2. При холодном кэше Vite
  // (новая папка RELAY_UI_ADDITIONAL_OUTPUT) страница перезагружается без #mockScenario и чата 101 не будет: повторяйте запуск с той же папкой
  await page.waitForFunction(() => window.__relayAdditional?.open && window.__relayAudit?.state().chatIds.includes('101'), undefined, { timeout: 60000 });
  await page.evaluate(() => window.__relayAudit.openChat('101')); await page.waitForFunction(() => window.__relayAudit.state().currentChatId === '101'); await page.waitForTimeout(800);
  const modes = [
    { id: 'fullhd', width: 1920, height: 1080, font: '16px', dir: 'ltr', motion: 'no-preference' },
    { id: 'narrow', width: 640, height: 900, font: '16px', dir: 'ltr', motion: 'no-preference' },
    { id: 'text200', width: 1920, height: 1080, font: '32px', dir: 'ltr', motion: 'no-preference' },
    { id: 'rtl-reduced', width: 1920, height: 1080, font: '16px', dir: 'rtl', motion: 'reduce' },
  ];
  const bodyKinds = ['contact', 'contact-edit', 'report-options', 'report-comment', 'country', 'password', 'formatting', 'safe-link', 'browser-close', 'mute', 'pin', 'delete-chat', 'attachment-photo', 'attachment-file', 'document', 'chat-language', 'delete-message'];
  for (const mode of modes) {
    await close(); await page.setViewportSize({ width: mode.width, height: mode.height }); await page.emulateMedia({ reducedMotion: mode.motion });
    await page.evaluate((current) => { window.document.documentElement.style.fontSize = current.font; window.document.documentElement.dir = current.dir; }, mode);
    for (const kind of bodyKinds) await run(kind + '-' + mode.id + '-body', kind, async () => {
      const modal = await open(kind);
      if (kind === 'document') await modal.locator('[class*="textLines"]').waitFor({ state: 'visible', timeout: 5000 });
      if (kind === 'attachment-photo') await page.waitForFunction(() => window.document.querySelector('.audit-additional-attachment img')?.naturalWidth > 0);
      const result = await geometry(modal); assert(result.controls > 0, 'Actual body needs controls'); assert(result.bodyText.length > 8, 'Actual body content is required');
      const screenshot = `ui-additional-modal-${label}-${kind}-${mode.id}.png`;
      await page.screenshot({ path: path.join(evidence, screenshot) });
      assert.equal(result.outsideViewport.length, 0, JSON.stringify(result.outsideViewport));
      return { mode, ...result, screenshot, exactBody: true };
    });
  }
  await close(); await page.setViewportSize({ width: 1920, height: 1080 }); await page.emulateMedia({ reducedMotion: 'no-preference' }); await page.evaluate(() => { window.document.documentElement.style.fontSize = '16px'; window.document.documentElement.dir = 'ltr'; });
  const cancelKinds = ['contact', 'contact-edit', 'password', 'safe-link', 'browser-close', 'mute', 'pin', 'delete-chat'];
  for (const kind of cancelKinds) for (const key of ['Enter', 'Space']) await run(kind + '-cancel-' + key.toLowerCase(), kind, async () => {
    const modal = await open(kind); const before = (await events()).length;
    const cancel = modal.locator('button').filter({ hasText: /Cancel|Отмена/i }).last(); await cancel.waitFor({ state: 'visible' }); await cancel.focus(); report.interactionTarget = await cancel.evaluate((element) => ({ focused: element === window.document.activeElement, markup: element.outerHTML.slice(0, 600) })); assert(report.interactionTarget.focused); await page.keyboard.press(key); await page.waitForTimeout(200);
    const delta = (await events()).slice(before); const unsafe = delta.filter((event) => !['close', 'closeNewContactDialog', 'toggleSafeLinkModal', 'clearTwoFaError', 'closeBrowserCloseConfirmationModal'].includes(event.name));
    assert.equal(unsafe.length, 0, JSON.stringify(delta)); assert.equal(await modal.count(), 0, 'Cancel closes actual component');
    return { key, activeTargetConfirmed: true, events: delta, protectedActionDelta: 0 };
  });
  await run('contact-empty-disabled', 'contact', async () => { const modal = await open('contact'); const disabled = modal.locator('button[disabled]'); assert.equal(await disabled.count(), 1); const before = await count('importContact'); await disabled.click({ force: true }); assert.equal(await count('importContact'), before); return { disabled: true, importDelta: 0 }; });
  await run('contact-valid-submit-once', 'contact', async () => { const modal = await open('contact'); const inputs = modal.locator('input'); await inputs.nth(0).fill('+79990000000'); await inputs.nth(1).fill('Synthetic'); await inputs.nth(2).fill('Contact'); await page.waitForTimeout(200); const before = await count('importContact'); const submit = modal.locator('button').filter({ hasText: /Done|Готово/i }); assert(await submit.isEnabled()); await submit.focus(); assert(await submit.evaluate((element) => element === window.document.activeElement)); await page.keyboard.press('Enter'); await page.waitForTimeout(150); assert.equal(await count('importContact'), before + 1); return { importDelta: 1 }; });
  await run('report-comment-empty-disabled', 'report-comment', async () => { const modal = await open('report-comment'); const disabled = modal.locator('button[disabled]'); assert.equal(await disabled.count(), 1); const before = await count('reportMessages'); await disabled.click({ force: true }); assert.equal(await count('reportMessages'), before); return { reportDelta: 0 }; });
  await run('report-comment-valid-once', 'report-comment', async () => { const modal = await open('report-comment'); await modal.locator('textarea').fill('Synthetic local report comment'); await page.waitForTimeout(200); const before = await count('reportMessages'); const submit = modal.locator('button').filter({ hasText: /Send|Отправить/i }); assert(await submit.isEnabled()); await submit.focus(); assert(await submit.evaluate((element) => element === window.document.activeElement)); await page.keyboard.press('Enter'); await page.waitForTimeout(150); assert.equal(await count('reportMessages'), before + 1); return { reportDelta: 1 }; });
  await run('report-option-once', 'report-options', async () => { const modal = await open('report-options'); const before = await count('reportMessages'); await modal.locator('.ListItem').first().click(); assert.equal(await count('reportMessages'), before + 1); return { reportDelta: 1 }; });
  await run('country-close-enter-safe', 'country', async () => { const modal = await open('country'); const before = await count('countrySubmit'); const button = modal.locator('button').first(); await button.focus(); report.interactionTarget = await button.evaluate((element) => ({ focused: element === window.document.activeElement, markup: element.outerHTML.slice(0, 600) })); assert(report.interactionTarget.focused); await page.keyboard.press('Enter'); await page.waitForTimeout(150); const delta = (await count('countrySubmit')) - before; assert.equal(delta, 0, 'Close Enter must not submit country selection'); return { submitDelta: delta }; });
  await run('country-search-and-limit', 'country', async () => { const modal = await open('country'); assert.equal(await modal.getByText('Hidden synthetic country').count(), 0); const input = modal.locator('input[type=text],input[type=search]').first(); await input.fill('Japan'); await page.waitForTimeout(150); assert(await modal.innerText().then((text) => text.includes('Japan') && !text.includes('Germany'))); await input.fill(''); await page.waitForTimeout(150); const before = await count('selectionLimit'); await modal.getByText('Germany', { exact: false }).click(); await modal.getByText('Japan', { exact: false }).click(); assert.equal(await count('selectionLimit'), before + 1); return { hiddenExcluded: true, filtered: true, limitDelta: 1 }; });
  await run('password-loading-confirm-disabled', 'password-loading', async () => { const modal = await open('password-loading'); await modal.locator('#sign-in-password').fill('synthetic-loading-password'); await page.waitForTimeout(200); const confirm = modal.locator('.confirm-dialog-button').first(); const before = await count('checkPassword'); const isDisabled = await confirm.isDisabled(); report.interactionTarget = { inputMethod: 'actual pointer click', isDisabled, markup: await confirm.evaluate((element) => element.outerHTML.slice(0, 600)) }; await confirm.click({ force: true }); await page.waitForTimeout(150); const checkDelta = (await count('checkPassword')) - before; assert.equal(checkDelta, 0, JSON.stringify({ isDisabled, checkDelta })); assert(isDisabled, 'Confirmation must be disabled during loading'); return { isDisabled, checkDelta }; });
  await run('password-visibility-keyboard', 'password', async () => { const modal = await open('password'); const toggle = modal.locator('.toggle-password'); const input = modal.locator('#sign-in-password'); assert.equal(await input.getAttribute('type'), 'password'); await toggle.focus(); report.interactionTarget = await toggle.evaluate((element) => ({ focused: element === window.document.activeElement, markup: element.outerHTML.slice(0, 600) })); assert(report.interactionTarget.focused); await page.keyboard.press('Enter'); await page.waitForTimeout(100); assert.equal(await input.getAttribute('type'), 'text', 'Visibility button Enter activates actual toggle'); return { toggled: true }; });
  for (const [kind, selector, action] of [['formatting', 'button', 'removeFormatting'], ['mute', '.dialog-buttons button', 'updateChatMutedState'], ['pin', '.dialog-buttons button', 'pinMessage'], ['browser-close', '.confirm-dialog-button', 'closeBrowserModal']]) await run(kind + '-confirm-once', kind, async () => { const modal = await open(kind); const button = kind === 'formatting' ? modal.locator(selector).last() : modal.locator(selector).first(); const before = await count(action); await button.focus(); report.interactionTarget = await button.evaluate((element) => ({ focused: element === window.document.activeElement, markup: element.outerHTML.slice(0, 600) })); assert(report.interactionTarget.focused); await page.keyboard.press('Enter'); await page.waitForTimeout(150); assert.equal(await count(action), before + 1, 'Intended callback exactly once'); return { callback: action, delta: 1 }; });
  await run('document-search-copy-and-close', 'document', async () => { const modal = await open('document'); await modal.locator('[class*="textLines"]').waitFor({ state: 'visible' }); await modal.locator('input[type=search]').fill('Alpha'); await page.waitForTimeout(150); assert.equal(await modal.locator('[class*="highlight"]').count(), 2); const copy = modal.locator('button').filter({ hasText: /Copy|Копировать/i }).first(); const before = await count('clipboard'); await copy.focus(); await page.keyboard.press('Enter'); await page.waitForTimeout(150); assert.equal(await count('clipboard'), before + 1); await page.keyboard.press('Escape'); await page.waitForTimeout(150); assert.equal(await page.locator('dialog[open]').count(), 0); return { matches: 2, copyDelta: 1, escapeClosed: true }; });
  await run('document-markdown-body', 'document', async () => { await close(); await page.evaluate(() => window.__relayAdditional.openDocument('md')); const modal = page.locator('dialog[open]').last(); await modal.locator('[class*="markdownContent"] h1').waitFor({ state: 'visible' }); assert.equal(await modal.locator('[class*="markdownContent"] h1').innerText(), 'Synthetic research'); return { actualMarkdown: true }; });
  for (const kind of ['contact', 'report-comment', 'country', 'password', 'formatting', 'safe-link', 'browser-close', 'mute', 'pin', 'delete-chat', 'document']) await run(kind + '-tab-contained', kind, async () => { const modal = await open(kind); let hostBoundaryCount = 0; for (const key of [...Array(8).fill('Tab'), ...Array(4).fill('Shift+Tab')]) { await page.keyboard.press(key); const state = await modal.evaluate((element) => ({ inside: element.contains(window.document.activeElement), nativeHost: element instanceof window.HTMLDialogElement && element.open && window.document.activeElement === window.document.body && !window.document.hasFocus() })); if (state.nativeHost) hostBoundaryCount += 1; assert(state.inside || state.nativeHost, 'Keyboard cannot focus background App'); } return { tabSteps: 8, reverseSteps: 4, hostBoundaryCount, isGate: hostBoundaryCount > 0, reason: hostBoundaryCount ? 'Native Chromium host Tab boundary; no background control reached' : undefined }; });
  await run('country-close-space-safe', 'country', async () => { const modal = await open('country'); const before = await count('countrySubmit'); const button = modal.locator('button').first(); await button.focus(); assert(await button.evaluate((element) => element === window.document.activeElement)); await page.keyboard.press('Space'); await page.waitForTimeout(150); assert.equal(await count('countrySubmit'), before); assert.equal(await modal.count(), 0); return { submitDelta: 0, closed: true }; });
  await run('password-visibility-pointer', 'password', async () => { const modal = await open('password'); const input = modal.locator('#sign-in-password'); await modal.locator('.toggle-password').click(); await page.waitForTimeout(150); assert.equal(await input.getAttribute('type'), 'text'); return { actualPointerToggled: true }; });
  for (const kind of ['country', 'formatting', 'safe-link']) await run(kind + '-native-host-boundary-proof', kind, async () => { const modal = await open(kind); const trace = []; for (let step = 0; step < 16; step += 1) { await page.keyboard.press('Tab'); const state = await modal.evaluate((element) => ({ inside: element.contains(window.document.activeElement), body: window.document.activeElement === window.document.body, hasDocumentFocus: window.document.hasFocus(), activeTag: window.document.activeElement?.tagName, dialogOpen: element.open })); trace.push(state); assert(state.inside || (state.body && !state.hasDocumentFocus && state.dialogOpen), JSON.stringify(state)); } const attemptedBackground = await modal.evaluate((element) => { const composer = window.document.querySelector('#editable-message-text'); composer?.focus(); return { backgroundFocused: window.document.activeElement === composer, inside: element.contains(window.document.activeElement), body: window.document.activeElement === window.document.body }; }); assert.equal(attemptedBackground.backgroundFocused, false, 'Native inertness blocks background composer'); return { isGate: true, reason: 'Native Chromium Tab can move to host browser UI; strict document containment needs platform-specific acceptance', trace, attemptedBackground, noBackgroundControlFocused: true }; });
  await run('password-empty-confirm-zero', 'password', async () => { const modal = await open('password'); const confirm = modal.locator('.confirm-dialog-button').first(); const before = await count('checkPassword'); assert(await confirm.isDisabled()); await confirm.click({ force: true }); await modal.locator('#sign-in-password').focus(); await page.keyboard.press('Enter'); await page.waitForTimeout(150); assert.equal(await count('checkPassword'), before); return { disabled: true, checkDelta: 0 }; });
  await run('password-whitespace-preserved-once', 'password', async () => { const modal = await open('password'); await modal.locator('#sign-in-password').fill(' a '); await page.waitForTimeout(200); const confirm = modal.locator('.confirm-dialog-button').first(); const before = await count('checkPassword'); assert(await confirm.isEnabled()); await confirm.focus(); await page.keyboard.press('Enter'); await page.waitForTimeout(150); assert.equal(await count('checkPassword'), before + 1); const latest = (await events()).filter((event) => event.name === 'checkPassword').at(-1); assert.deepEqual(latest.detail, { length: 3, preservesFixtureWhitespace: true }); return { checkDelta: 1, preservesFixtureWhitespace: true }; });
  await run('password-visibility-space-repeat-once', 'password', async () => { const modal = await open('password'); const toggle = modal.locator('.toggle-password'); const input = modal.locator('#sign-in-password'); const before = await count('checkPassword'); await toggle.focus(); await page.keyboard.down('Enter'); await page.waitForTimeout(100); assert.equal(await input.getAttribute('type'), 'text'); await page.keyboard.down('Enter'); await page.waitForTimeout(100); assert.equal(await input.getAttribute('type'), 'text', 'Repeated held Enter does not toggle again'); await page.keyboard.up('Enter'); await page.keyboard.press('Space'); await page.waitForTimeout(100); assert.equal(await input.getAttribute('type'), 'password'); assert.equal(await count('checkPassword'), before); return { heldRepeatIgnored: true, spaceToggledOnce: true, checkDelta: 0 }; });
  await run('country-filter-enter-once', 'country', async () => { const modal = await open('country'); const before = await count('countrySubmit'); const filter = modal.locator('input[type=text],input[type=search]').first(); await filter.fill('Russia'); await filter.focus(); await page.keyboard.press('Enter'); await page.waitForTimeout(150); assert.equal(await count('countrySubmit'), before + 1); return { submitDelta: 1 }; });
  await run('country-checkbox-enter-zero', 'country', async () => { const modal = await open('country'); const before = await count('countrySubmit'); const checkbox = modal.locator('input[type=checkbox]').nth(1); await checkbox.focus(); await page.keyboard.press('Enter'); await page.waitForTimeout(100); assert.equal(await count('countrySubmit'), before); await page.keyboard.press('Space'); await page.waitForTimeout(100); assert.equal(await checkbox.isChecked(), true); return { enterSubmitDelta: 0, spaceSelected: true }; });
  await run('country-confirm-enter-once', 'country', async () => { const modal = await open('country'); const before = await count('countrySubmit'); const confirm = modal.locator('button').last(); await confirm.focus(); await page.keyboard.press('Enter'); await page.waitForTimeout(150); assert.equal(await count('countrySubmit'), before + 1); return { submitDelta: 1 }; });
  await run('browser-close-default-focus-safe', 'browser-close', async () => { const modal = await open('browser-close'); const buttons = modal.locator('.confirm-dialog-button'); assert(await buttons.last().evaluate((element) => element === window.document.activeElement)); const before = await count('closeBrowserModal'); await page.keyboard.press('Enter'); await page.waitForTimeout(150); assert.equal(await count('closeBrowserModal'), before); return { initialCancelFocus: true, protectedActionDelta: 0 }; });
  await run('browser-close-pointer-once', 'browser-close', async () => { const modal = await open('browser-close'); const before = await count('closeBrowserModal'); await modal.locator('.confirm-dialog-button').first().click(); assert.equal(await count('closeBrowserModal'), before + 1); return { callbackDelta: 1 }; });
  report.unhandled = await page.evaluate(() => window.__relayUnhandled);
} catch (error) { report.fatal = String(error); console.error(error); }
finally {
  await browser?.close(); await server.close();
  report.summary = { total: report.cases.length, pass: report.cases.filter((item) => item.status === 'pass').length, fail: report.cases.filter((item) => item.status === 'fail').length, pageErrors: report.errors.length, gates: report.cases.filter((item) => item.status === 'gate').length };
  await writeFile(path.join(evidence, `ui-additional-modal-${label}.json`), JSON.stringify(report, undefined, 2) + '\n'); console.log(JSON.stringify(report.summary)); if (report.fatal || report.summary.fail || report.errors.length || report.unhandled?.length) process.exitCode = 1;
}

